alias: Machine à laver
description: ""
trigger:
  - type: power
    platform: device
    device_id: <device_id>
    entity_id: sensor.machine_a_laver_current_power
    domain: sensor
    for:
      hours: 0
      minutes: 1
      seconds: 30
    below: 2
condition: []
action:
  - service: tts.google_translate_say
    data:
      entity_id: <entity_id>
      message: Le linge est propre ! Il faut vider la machine.
      cache: false
  - service: notify.telegram_groupe
    data:
      message: 🧺 Le linge est propre ! Il faut vider la machine.
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.machine_a_laver
mode: single
